### ISSUE TITLE
Improve Detailed Search

### ISSUE THREAD

**Issue by RatiJeb** [RatiJeb/parallel_corpus#15]
"გაფართოებულ ძიებაში ფილტრების ველები ვიწროა, ასევე ზოგი მათგანი აბრუნებს 'არ მოიძებნა'-ს.
ასევე ჩამოსასქროლი არ აქვს რომ სხვა ფილტრები გამოვაჩინოთ მარტივად, ქვევით რაც არის."

**Comment by RatiJeb** [comment]
@erekle0004 დაამატე აღწერაში რაც აკლია.

**Comment by RatiJeb** [comment]
ძიების აკეცვა

**Comment by RatiJeb** [comment]
ფილტრების გამყოფი ხაზების ჩამატება დიზაინის მიხედვით

**Comment by erekle0004** [comment]
> @erekle0004 დაამატე აღწერაში რაც აკლია.

@RatiJeb 
ფილტრი ჩვეულებრივ დიზაინის მიხედვით.
**დამატებითი აღწერა:**
- ჩვეულებრივი მარტივი ძიება ეძებს ყველა დამთხვევას, მაგ: ვეძებ "ბავშვ" და უნდა მაჩვენოს ყველა სიტყვა თუ წინანდადება სადაც "ბავშვ' არის გამოყენებული.
- დეტალურ ძიებაში ჯერ ლემა არ გვჭირდება,
- დავამტოთ, "ზუსტი დამთხვევა და ყველა დამთხვევა" დასაწყისში.
- ფილტრის გვერდით შეკეცვის ან აკეცვის ფუნქცია
